### ISSUE TITLE
The Boring Education | Fix bug of footer

### ISSUE THREAD

**Issue by imsks** [The-Boring-Education/TBE-Web#133]
Task Link - https://theboringeducation.notion.site/The-Boring-Education-Fix-bug-of-footer-bdc0e5413ac849daa0b1d3f577cac94d?pvs=4

**Comment by 000adarsh** [comment]
assign it to me

**Comment by navyasrisangem** [comment]
Please assign this to me.

**Comment by imsks** [comment]
@000adarsh, you can read contributing.md, fix the bug, and raise a pull request.

**Comment by ashishpathak2** [comment]
@imsks  Could you please review my PR? Thank you!
