### ISSUE TITLE
In JavaScript Interview Questions Issue / Question have issue

### ISSUE THREAD

**Issue by harshad00** [The-Boring-Education/TBE-Web#135]
In JavaScript Interview Questions have an Issue like (the question is) "What is an Event Loop?" but the given Answer is Arrow Function Or Normal Function. you check in the Image.

**Comment by harshad00** [comment]
![Screenshot 2024-12-14 150613](https://github.com/user-attachments/assets/52c8e415-f351-4a0d-864d-98c86a8fb64d)

**Comment by imsks** [comment]
Updated.
