### ISSUE TITLE
Design Header Component

### ISSUE THREAD

**Issue by imsks** [The-Boring-Education/TBE-Web#3]
In this Task, We start with Designing the Header Component.

We want a minimal version that looks like our existing header on the [Landing page](https://www.theboringeducation.com/)
![Image](https://github.com/The-Boring-Education/TBE-Web/assets/29145481/60768479-a314-4203-98c1-cc09808fb17f)

**Comment by Nikhil273** [comment]
Here is the Figma Link 
https://www.figma.com/proto/NXOAhuyi9cfPxWk5wWAbCt/Tbe---OpenSource?page-id=0%3A1&type=design&node-id=1-2&viewport=578%2C495%2C0.5&t=GmTkEWawQx0jLBM7-1&scaling=min-zoom&mode=design
@imsks
