### ISSUE TITLE
Design Hero Section

### ISSUE THREAD

**Issue by imsks** [The-Boring-Education/TBE-Web#4]
Now let's design the Hero Section of the Landing Page.

![Image](https://github.com/The-Boring-Education/TBE-Web/assets/29145481/dfd3ea27-0c67-4d36-8cca-9ebb162621ab)

**Comment by imsks** [comment]
@kaustubh2332 You can design a better version of this though. Just make sure it's not too complex

**Comment by Nikhil273** [comment]
https://www.figma.com/file/L5sPdtwg8gCTyQ4ali4Wpg/Tbe--Hero-Section?type=design&node-id=0%3A1&mode=design&t=E0nJIcu5WY7NhqdW-1
