### ISSUE TITLE
The Boring Interview Prep | Landing Page UI

### ISSUE THREAD

**Issue by imsks** [The-Boring-Education/TBE-Web#49]
Task - https://theboringeducation.notion.site/The-Boring-Interview-Prep-Landing-Page-UI-12832c1a15e280119161f9247d837c54?pvs=4

Contributing here for the first time? Read the CONTRIBUTING.md first

**Comment by harshad00** [comment]
Hello imsks,  I am interested in this project and it's my first time to open source. Can you help me with this The Boring Interview has not been repo can you help with that?

**Comment by imsks** [comment]
Hey @harshad00 Please read https://github.com/The-Boring-Education/TBE-Web/blob/production/CONTRIBUTING.md
