### ISSUE TITLE
Design Why We Building The Boring Projects? Section?

### ISSUE THREAD

**Issue by imsks** [The-Boring-Education/TBE-Web#5]
Design a Section that talks about Why The Boring Project Exists.

You'll use Cards for this section. You can take a look at [here](https://www.theboringeducation.com/) and see the "What We Do Differently" section. Something like that we can design.

![Image](https://github.com/The-Boring-Education/TBE-Web/assets/29145481/f80d55fa-0551-4212-a088-9196328e34ae)
![Image](https://github.com/The-Boring-Education/TBE-Web/assets/29145481/39918252-f911-47bb-9347-1eafe3e61e4c)

**Comment by abhisekcode** [comment]
https://www.figma.com/file/q9d8YR9QmR6pmyJep9NJbs/Why-we-are-Building-Boring-Projects?type=design&node-id=0%3A1&mode=design&t=4h3Q4ZiFS1DdItGx-1

**Comment by imsks** [comment]
@abhisekcode this looks good but doesn't fit for this section. Design something like 

![Image](https://github.com/The-Boring-Education/TBE-Web/assets/29145481/f06d71e0-e09b-4937-b638-81ef67fdd64b)

Always check if you can reuse components in Design. That saves lot of time for us.

**Comment by abhisekcode** [comment]
sure, i will pick this.
