### ISSUE TITLE
The Boring Interview Prep | User Sheet Database Model

### ISSUE THREAD

**Issue by imsks** [The-Boring-Education/TBE-Web#53]
Task - https://theboringeducation.notion.site/The-Boring-Interview-Prep-User-Sheet-Database-Models-12832c1a15e280d1a9daded3149379e7?pvs=4

Contributing here for the first time? Read the CONTRIBUTING.md first

**Comment by POBOROJO** [comment]
Can you please assign me this issue ? I want to contribute.

**Comment by imsks** [comment]
Feel free to contribute. No need to assign. One suggestion similar feature
is implemented in Shiksha. Please look into it

**Comment by POBOROJO** [comment]
Ok bhaiya sure

**Comment by imsks** [comment]
Implemented.
