### ISSUE TITLE
Design Our Projects Section

### ISSUE THREAD

**Issue by imsks** [The-Boring-Education/TBE-Web#6]
We need to design a section like below - 
![Image](https://github.com/The-Boring-Education/TBE-Web/assets/29145481/117f6855-2641-4cd2-934b-6d6eb2b0f831)

**Comment by imsks** [comment]
@iam-shakeebkhan You can design something like this. Check the Website for more.
![Image](https://github.com/The-Boring-Education/TBE-Web/assets/29145481/c0fdc613-b695-4f10-867f-1e5c00602bdf)

**Comment by ghost** [comment]
https://www.figma.com/file/CIWddMZR1lBQzEhlm9JanO/our-Programs-%26-Footer?type=design&node-id=0%3A1&mode=design&t=FI0r6NR1xvNb4MRD-1

**Comment by imsks** [comment]
@iam-shakeebkhan The Above image was for Reference. We're designing Cards for Projects not courses. That's an old Design. I'll take this up.
