### ISSUE TITLE
Shiksha | My Courses Page in Shiksha

### ISSUE THREAD

**Issue by imsks** [The-Boring-Education/TBE-Web#67]
Task - https://theboringeducation.notion.site/Shiksha-My-Courses-Page-in-Shiksha-12832c1a15e28042878cfb763158b521?pvs=4

Please read contributing.md before making any contributions.

**Comment by harshad00** [comment]
This UI is implement in hear `shikshaExplore: '/shiksha/explore',` or make new one rout
