### ISSUE TITLE
Design Footer

### ISSUE THREAD

**Issue by imsks** [The-Boring-Education/TBE-Web#7]

**Comment by imsks** [comment]
Design the Basic Footer. 

![Image](https://github.com/The-Boring-Education/TBE-Web/assets/29145481/53928f63-bb85-4923-a01e-a8a1f047b595)

**Comment by patil-minakshi** [comment]
https://www.figma.com/file/4CGegZ9A2nAlYTNx8Zm4Yq/e-learning-landing-page?type=design&node-id=0%3A1&mode=design&t=WwtLxTf2Qm6L0kyI-1

**Comment by MPrashant1100** [comment]
https://www.figma.com/file/4CGegZ9A2nAlYTNx8Zm4Yq/Design-Footer?type=design&node-id=0-1&mode=design&t=Oyf3gdf8DwvzlOEn-0

**Comment by imsks** [comment]
@MPrashant1100 Your Figma File looks exactly the same. Moving ahead with @patil-minakshi
