### ISSUE TITLE
Create Landing Page for TBP

### ISSUE THREAD

**Issue by imsks** [The-Boring-Education/TBE-Web#8]
Create a Landing Page in Next.js for The Boring Projects.  Check Master doc for Figma Design. 

Create the page and Add a Header Component. 

The header component is already created. You'll use the same component.

**Comment by Adnaanlegend** [comment]
Can i attempt?

**Comment by imsks** [comment]
> Can i attempt?

Hey Adnan, Sure. You can start by joining the community where you'll learn more about contributing here.

Link - https://theboringeducation.notion.site/The-Boring-Open-Source-Master-Doc-8171f19257fd4ef99b7287555eb5062b?pvs=74
